server:
  port: 8081

spring:
  application:
    name: "EasyEvent"
  datasource:
    url: jdbc:postgresql://localhost:5432/easyevent
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  http:
     encoding:
      charset: UTF-8
      enabled: true
      force: true

security:
  oauth2:
    client:
      client-secret: HI-XYx1MbbcWLxtj4SFOi4i7
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      scope: email,profile,openid
      client-id: 635082597214-blsblaot5ddl4pmi56jkuu9s3o4mum3d.apps.googleusercontent.com
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true

logging:
  level:
    org.springframework: ERROR
    com.easyevent: INFO
  file: logs.txt

jwt:
  token:
    secret: easyevent
    expiredTime: 36000000