server:
  port: 8080

spring:
  application:
    name: "EasyEvent"
  datasource:
    url: jdbc:postgresql://localhost:5432/easyevent
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  http:
     encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework: ERROR
    com.easyevent: INFO
  file: logs.txt